### PR TITLE
V3 to v4

### PR DESCRIPTION
**Pull request by mkuzak**
Updated notebooks to new notebook format.
This might not work with older versions of IPython notebook, so you might consider not integrating this pull request.

### CODE REVIEW

**Comment by jvns** [comment]
hey thanks for this! To merge this, we'll also need to update the installation instructions in the README to note that the you need a newer version of IPython to use the new notebook format. Right now it says this requires IPython >= 1.0 which wouldn't be true anymore.

**Comment by mkuzak** [comment]
according to [this](http://ipython.org/ipython-doc/3/whatsnew/version3.html), v4 should work with IPython >= 2.4
should I add the changes to README.md and redo the pull request?

**Comment by jvns** [comment]
If you want! If you don't, then I'm happy to do it myself eventually.

**Comment by mkuzak** [comment]
updated README
also removed some whitespace at the end of lines in that file

**Comment by jvns** [comment]
Thanks very much!

**Pull request merged**
