### PR TITLE
Dockerise

### PR DESCRIPTION
**Pull request by mkuzak**
I've added a Docker file to build a docker image with ipython and cookbook in it.
I've also added the description on how to use it in `README.md`.
You can connect your jvns/pandas-cookbook repository with respective repository on hub.docker and it will build fully functional container with ipython and cookbook. That way no one will need to build the image themselves locally, just run `docker pull jvns/pandas cookbook`.

### CODE REVIEW

**Comment by jvns** [comment]
This is interesting, thanks! I just tried this out, and when I follow the instructions I just see a `images/` directory in the ipython notebook root directory. Do you know what's going on?

**Comment by mkuzak** [comment]
Looks like the images directory contents have been copied together with python notebooks into cookbook dir.
Now they're in cookbook/images dir, as in your [original notebook](http://nbviewer.ipython.org/github/jvns/pandas-cookbook/tree/master/cookbook/). Is this what you meant?

**Comment by mprentic-harris** [comment]
Good stuff!

**Comment by jvns** [comment]
sorry for the delay -- just merged this!

**Pull request merged**
